### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Jogai** [distros/bootstrap-less#5]
Repo says its 3.3.5, but in bootstrap.js it says 3.3.4:

```
/*!
 * Bootstrap v3.3.4 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
```

Can you update the npm package to use 3.3.6 for everything?

**Comment by Jogai** [comment]
Or 3.3.7?

**Comment by Aaike** [comment]
This project is not maintained but please feel free to submit pull requests if you need an update or some other changes to this repository.

**Comment by Jogai** [comment]
Looks like the official bootstrap package distributes less as well, so there's no need anymore.
