### ISSUE TITLE
license

### ISSUE THREAD

**Issue by crooy** [distros/bootstrap-less#6]
Hi,

stupid problem but i need your repo to have a license could you add one? I guess you can just copy the bootstrap license

**Comment by brettcannon** [comment]
Replying to bump this as I'm running into this as well.

**Comment by ariel11** [comment]
Is the license for your project the MIT License, as some of the files point back to the Bootstrap MIT License?

**Comment by Aaike** [comment]
sorry for slow response everyone, i have added a license file which is a direct copy of the bootstrap license.

**Comment by brettcannon** [comment]
Thank you!
