### ISSUE TITLE
Bootstrap dependancies in NPM

### ISSUE THREAD

**Issue by sheam** [distros/bootstrap-less#7]
I have a couple packages that have a dependency on the bootstrap node module. However because I am using the Bootstrap-less package, I don't really need the plain bootstrap package.

The problem is that NPM is constantly complaining about an unmet bootstrap dependency. Is there a way around this? Or just I just concede and install the bootstrap dependency was well, even if it is redundant with the bootstrap-less package?

**Comment by Aaike** [comment]
This project is not maintained but please feel free to submit pull requests if you need an update or some other changes to this repository
